<a href="https://colab.research.google.com/github/PRO-AnkitVerma/pytorch-tutorials/blob/main/01_tensor_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Awesome PyTorch

An short introduction about PyTorch and about the chosen functions. 

- torch.abs
- torch.zeros

Before we begin, let's install and import PyTorch

In [1]:
# Import torch and other required modules
import torch

## Function 1 - torch.abs

Computes the absolute value of each element in input

In [3]:
# Example 1 - working 
x = torch.tensor(1.)
y = torch.tensor([1., 2.])

print(torch.abs(x))
print(torch.abs(y))

tensor(1.)
tensor([1., 2.])


In [4]:
# Example 2 - working
x = torch.tensor(-1.)
y = torch.tensor([-1., -2.])

print(torch.abs(x))
print(torch.abs(y))

tensor(1.)
tensor([1., 2.])


In [ ]:
# Example 3 - breaking 
torch.abs([[1, 2], [3, 4.]]) # it works on tensors but not on lists

ValueError: expected sequence of length 2 at dim 1 (got 3)

Closing comments about when to use this function

Let's save our work using Jovian before continuing.

In [ ]:
!pip install jovian --upgrade --quiet

In [ ]:
import jovian

In [ ]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/01-tensor-operations" on https://jovian.ai/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/aakashns/01-tensor-operations


'https://jovian.ai/aakashns/01-tensor-operations'

## Function 2 - torch.zeros

Returns a tensor filled with the scalar value 0, with the shape defined by the variable argument size

In [14]:
# Example 1 - working
x = torch.zeros(1,2,3, dtype=torch.float64)

x

tensor([[[0., 0., 0.],
         [0., 0., 0.]]], dtype=torch.float64)

Explanation about example

In [15]:
# Example 2 - working
x = torch.zeros((1,2,3), dtype=torch.float64)

x

tensor([[[0., 0., 0.],
         [0., 0., 0.]]], dtype=torch.float64)

Explanation about example

In [16]:
# Example 3 - breaking 
x = torch.zeros(dtype=torch.float64, 1,2,3,)

x

SyntaxError: ignored

Explanation about example

Closing comments about when to use this function

In [ ]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/01-tensor-operations" on https://jovian.ai/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/aakashns/01-tensor-operations


'https://jovian.ai/aakashns/01-tensor-operations'

## Conclusion

Summarize what was covered in this notebook, and where to go next

## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for tensor operations: https://pytorch.org/docs/stable/torch.html
* ...

In [ ]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
